# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import file_storage_pb2 as file__storage__pb2


class FileStorageStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadFile = channel.unary_unary(
                '/FileStorage/UploadFile',
                request_serializer=file__storage__pb2.Content.SerializeToString,
                response_deserializer=file__storage__pb2.UploadResponse.FromString,
                )
        self.DownloadFile = channel.unary_unary(
                '/FileStorage/DownloadFile',
                request_serializer=file__storage__pb2.DownloadRequest.SerializeToString,
                response_deserializer=file__storage__pb2.Content.FromString,
                )
        self.RequestContentProviderMutex = channel.unary_unary(
                '/FileStorage/RequestContentProviderMutex',
                request_serializer=file__storage__pb2.MutexRequest.SerializeToString,
                response_deserializer=file__storage__pb2.MutexResponse.FromString,
                )
        self.RequestUserMutex = channel.unary_unary(
                '/FileStorage/RequestUserMutex',
                request_serializer=file__storage__pb2.MutexRequest.SerializeToString,
                response_deserializer=file__storage__pb2.MutexResponse.FromString,
                )


class FileStorageServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestContentProviderMutex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestUserMutex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileStorageServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadFile,
                    request_deserializer=file__storage__pb2.Content.FromString,
                    response_serializer=file__storage__pb2.UploadResponse.SerializeToString,
            ),
            'DownloadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DownloadFile,
                    request_deserializer=file__storage__pb2.DownloadRequest.FromString,
                    response_serializer=file__storage__pb2.Content.SerializeToString,
            ),
            'RequestContentProviderMutex': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestContentProviderMutex,
                    request_deserializer=file__storage__pb2.MutexRequest.FromString,
                    response_serializer=file__storage__pb2.MutexResponse.SerializeToString,
            ),
            'RequestUserMutex': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestUserMutex,
                    request_deserializer=file__storage__pb2.MutexRequest.FromString,
                    response_serializer=file__storage__pb2.MutexResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FileStorage', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FileStorage(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FileStorage/UploadFile',
            file__storage__pb2.Content.SerializeToString,
            file__storage__pb2.UploadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DownloadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FileStorage/DownloadFile',
            file__storage__pb2.DownloadRequest.SerializeToString,
            file__storage__pb2.Content.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RequestContentProviderMutex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FileStorage/RequestContentProviderMutex',
            file__storage__pb2.MutexRequest.SerializeToString,
            file__storage__pb2.MutexResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RequestUserMutex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FileStorage/RequestUserMutex',
            file__storage__pb2.MutexRequest.SerializeToString,
            file__storage__pb2.MutexResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
