# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file_storage.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x66ile_storage.proto\"7\n\x12RequestMutexParams\x12\x12\n\nprocess_id\x18\x01 \x01(\x05\x12\r\n\x05token\x18\x02 \x01(\x05\"/\n\rMutexResponse\x12\x0f\n\x07granted\x18\x01 \x01(\x08\x12\r\n\x05token\x18\x02 \x01(\x05\"(\n\x12ReleaseMutexParams\x12\x12\n\nprocess_id\x18\x01 \x01(\x05\")\n\x07\x43ontent\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"0\n\x0eUploadResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"#\n\x0f\x44ownloadRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t2\xcc\x01\n\x0b\x46ileStorage\x12\x33\n\x0cRequestMutex\x12\x13.RequestMutexParams\x1a\x0e.MutexResponse\x12\x33\n\x0cReleaseMutex\x12\x13.ReleaseMutexParams\x1a\x0e.MutexResponse\x12\'\n\nUploadFile\x12\x08.Content\x1a\x0f.UploadResponse\x12*\n\x0c\x44ownloadFile\x12\x10.DownloadRequest\x1a\x08.Contentb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_storage_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUESTMUTEXPARAMS']._serialized_start=22
  _globals['_REQUESTMUTEXPARAMS']._serialized_end=77
  _globals['_MUTEXRESPONSE']._serialized_start=79
  _globals['_MUTEXRESPONSE']._serialized_end=126
  _globals['_RELEASEMUTEXPARAMS']._serialized_start=128
  _globals['_RELEASEMUTEXPARAMS']._serialized_end=168
  _globals['_CONTENT']._serialized_start=170
  _globals['_CONTENT']._serialized_end=211
  _globals['_UPLOADRESPONSE']._serialized_start=213
  _globals['_UPLOADRESPONSE']._serialized_end=261
  _globals['_DOWNLOADREQUEST']._serialized_start=263
  _globals['_DOWNLOADREQUEST']._serialized_end=298
  _globals['_FILESTORAGE']._serialized_start=301
  _globals['_FILESTORAGE']._serialized_end=505
# @@protoc_insertion_point(module_scope)
